### ISSUE TITLE
latency on receiving audio when using plugin

### ISSUE THREAD

**Issue by virusmarathe** [BananaHemic/Mumble-Unity#12]
It looks like there is a quarter to half second latency increase when comparing receiving the plugin audio to standalone mumble. Is this something that can be reduced or played with on my end? Or is this just the overhead from talking through Unity?
Worth noting that I am in a LAN setting so the latency shouldn't be network related, and a mumble client receives audio quickly.

**Comment by Bananahavoc** [comment]
Can you try lowering InitialSampleBuffer in AudioDecodingBuffer.cs? There's always going to be a tradeoff between stream stability and latency, but if you're using this over LAN, then you could probably get away with using an initial buffer of 1.

From my tests (which may be wrong in some way) I get slightly lower latency when receiving audio in Unity than I do in the Mumble desktop client.

**Comment by virusmarathe** [comment]
Thanks! That is exactly the variable I was looking for.
