### ISSUE TITLE
OOB Testing?

### ISSUE THREAD

**Issue by recursiveDream** [BananaHemic/Mumble-Unity#13]
I've downloaded/cloned the latest and built an executable running for x64 out of Unity 2017.3.  I can hear myself echo back, and can see a connection success to my local windows mumble server, but can't seem to communicate with anyone.

I've noticed a slew of debug prints with empty packets; is there something additional I need besides setting the threshold to 0 before getting the test to work out of box?

**Comment by Bananahavoc** [comment]
Hmm, there shouldn't be anything additional to get it set up. Can you try setting:
In MumbleTester
- Use Random Username: True
- Use Local Loopback: False
- Use Synthetic Source: False
- Connect Asynchronously: True
In MumbleMic
- Send Audio On Start: True:
- Mic Number To Use: 0
- Voice Sending Type: Always Send

If that still fails, can you send a log of the console output?

**Comment by Black-Alpha** [comment]
@recursiveDream  I had the same issue debugging on console and the solution @BananaHemic provided worked as far as the errors go about empty or wrong packet size. 

I've haven't gone though the source to check myself, but this is what I have done so far:

1. build working mumble server (linux)
2. test server with 'Plumble - Mumble VOIP (Free)' via android <- also works
3. build mumble-unity android buid (works in a way)

with plumble I hear audio clearly sent from mumble-unity to plumble
with mumble-unity build I can't hear audio clearly sent from plumble to mumble-unity
with mumble-unity build I can't hear audio clearly sent from mumble unity to mumble-unity

if there is any way I can provide help with audio quality let me know, take care -peace

**Comment by Bananahavoc** [comment]
Is it that you hear no audio, or is it that the audio isn't as clear as you'd expect?
Any logs or audio samples would be very helpful.

**Comment by Black-Alpha** [comment]
The audio decoded through unity-mumble isn't clear 
[Voice_180429.zip](https://github.com/BananaHemic/Mumble-Unity/files/1959344/Voice_180429.zip)
But the audio transmitted from unity-mumble is crystal clear (tested via Plumble)

**Comment by Bananahavoc** [comment]
Wow, that is definitely quite messed up.

I just tested sending audio from Plumble Free on Android to mumble-unity in editor on Windows x64, and the audio was quite clear for me.

Are there any logs that look unusual? Could you try disabling speex in your Murmur config? Does decoding audio work if it's from Mumble running on windows? I wish I could be of more help here, but it's hard to debug an issue without being able to reproduce it.

**Comment by Black-Alpha** [comment]
Understood and yes,  decoded audio works from Mumble running on windows.
I also have reproduced the same result you mentioned ;

> I just tested sending audio from Plumble Free on Android to mumble-unity in editor on Windows x64, and the audio was quite clear for me.

tested with Plumble to unity-mumble (console) : clear audio 
tested with unity-mumble (android) to unity-mumble (console) :  clear audio 
 
**the audio is only jumbled when decoded on unity-mumble (android)**

from the logcat I only found 3 types of errors:

- 04-30 04:12:13.092 17845-17860/? E/Unity: Unable to find AudioPluginOculusSpatializer
- 04-30 04:12:13.094 17845-17860/? E/Unity: Unable to find libAudioPluginOculusSpatializer
- (multiple) 04-30 04:13:10.775 17845-17934/? E/Unity: Crypt: 4

[logcat.txt](https://github.com/BananaHemic/Mumble-Unity/files/1959895/logcat.txt)

as for the server I have set "opusthreshold=0" via Murmur.ini, but I'm not sure if that is what you are referring to when you mentioned the following: 
> try disabling speex in your Murmur config

**Comment by Black-Alpha** [comment]
SOLVED (clear audio via unity-mumble android)
within MumbleAudioPlayer.cs : 

        void Start()
        {
            //print("outout rate " + AudioSettings.outputSampleRate);
            if (Application.platform == RuntimePlatform.Android)
            {
                GetComponent<AudioSource>().pitch = 2;
            }
        }

@BananaHemic  thank you for you active assistance .

**Comment by Bananahavoc** [comment]
I think that your solution works because your device is using an output sample rate of 24k, whereas right now Mumble-Unity expects an output sample rate of 48k. This also explains why there are so many dropped buffers listed in your logs.

I'll set up Mumble-Unity to no longer make an assumption of output sample rate and push that later today.
