### ISSUE TITLE
Please help!. I can not hear anything

### ISSUE THREAD

**Issue by hdv0112** [BananaHemic/Mumble-Unity#17]
Please help me. In the Script: UdpPacketReader.cs
Function:
public byte[] ReadBytes(int length)
        {
            byte[] buffer = new byte[length];
            var read = _inner.Read(buffer, 0, length);
            if (length != read)
                return null;
            return buffer;
        }
Always return null. Because "read = _inner.Read(buffer, 0, length)" always return 101, with every value "length".
Thanks so much for your help.

**Comment by Bananahavoc** [comment]
That's interesting because I haven't experienced any issues there. Could you tell me a bit more about how you're using this asset? For instance, are you receiving audio from Mumble-Unity, or a different Mumble client?

**Comment by hdv0112** [comment]
Thanks for your reply. I use Plumble - Mumble VOIP App android to send voice, and use Mumble-Unity to listen. The audio data is transmitted, but can not be read and converted to audio, because the problem in above Scripts. Do you think the problem from Plumble - Mumble VOIP App or above Script. Thanks so much!

**Comment by Bananahavoc** [comment]
I use Plumble with this asset, so my guess is that there's a configuration issue somewhere.

Do you know if you're streaming Opus or Speex audio? This asset doesn't support Speex because it's a fairly outdated client. If you are able to change settings for the Murmur server, you can force it to only use Opus and not Speex anywhere.

If you are using Opus, can you tell me what the value of "size" is before ReadBytes is called?

**Comment by hdv0112** [comment]
Hi BananaHemic, now I used Plumple with this asset. And I have heard the sound, but the signal is just noise. Ex: ss..sss..ssss

**Comment by Bananahavoc** [comment]
Did you confirm that you're using Opus?
Do you still get noise when using local loopback (It's a setting in MumbleTester)?
Did you change anything to make noise come through as opposed to nothing?

**Comment by hdv0112** [comment]
Hi BananaHemic. 
I'm sure using Opus, using local loopback. Do I need to configure anything?
Thanks

**Comment by Bananahavoc** [comment]
The asset _should_ work out of the box without any configuring other than enforcing Opus everywhere.

- Do you still only get noise if "Use synthetic source" is on?
- Do you get a log message saying what frequencies the microphone supports?
- If you have more than one mic available on your machine, can you try cycling through "Mic Number To Use" in Mumble Microphone?
- Can you post the full logs?

**Comment by hdv0112** [comment]
Thank you very much for the great help from you. After all day adjusting, I have successfully build it. Thanks so much again!!!

**Comment by Bananahavoc** [comment]
No problem!

Could you please say what the issue was? I just want to help other people who may be similarly stuck
