### ISSUE TITLE
Did Mumble -Unity  Supports Unity 2018?

### ISSUE THREAD

**Issue by CLOUDFIRE91** [BananaHemic/Mumble-Unity#21]
Hi All 

I am new to  Mumble. I have downloaded the Mumble Unity assets. and i have run on Unity 2018.
When i try to  build in ios Platform. the xcode project is not created.. I cant run in Xcode. 
So What i have to Do to create Xcode project.

Did Mumble Unity Projects in Github Supports Unity 2018 Version?

**Comment by Bananahavoc** [comment]
I think the main reason why you can't run it in Xcode is that I don't have Opus compiled for ios. This shouldn't be too tough, as Opus is popular open source software that supports ios, but I don't have any ios device with which to test/compile.

If you could get Opus compiled into an ios package, that would probably solve your problem and I would happily merge that change into the project

**Comment by hdv0112** [comment]
I have build Opus lib and run successfully on ios. If you need, you can download it:
https://drive.google.com/open?id=1q__b2Tg1v1dgq7bmlpK_ec4ZExvxHieL
