### ISSUE TITLE
Make stereo audio

### ISSUE THREAD

**Issue by Axios16** [BananaHemic/Mumble-Unity#24]
I made a simple scene to test the 3d positional audio and it works great, but how can I turn this audio into stereo? So I can hear the voice depending on the camera (listener) orientation

**Comment by Bananahavoc** [comment]
You would likely need to use an audio spatializer, you might want to check out:

1. https://developer.oculus.com/downloads/package/oculus-spatializer-unity/
2. https://docs.unity3d.com/Manual/VRAudioSpatializer.html

**Comment by Axios16** [comment]
Tried it, but doesn't seem to work. Without any spatializer, if I make a GameObject with an audiosource and a clip, the audio is played in 3d, but with the prefab spawned by the Tester doesn't do this. Any idea?

**Comment by Bananahavoc** [comment]
Make sure that the AudioSource that's created has Spatialize set to true, and that "Spatial blend" is set to 3D

**Comment by Axios16** [comment]
Yeah, found it. Now it works. Thank you!

**Comment by twchristian** [comment]
@Axios16 or @BananaHemic can you elaborate? I'm trying to do the same thing, and the sound adjusts for distance but not direction. I can drop an audio clip into a manually placed MumbleAudioPlayerPrefab with the same settings and directional stereo balance works. But if I send the clip through Mumble it only attenuates volume. So it must be something to do with the way the audio data is fed to the AudioSource, but I can't even figure out how that is done. The only references to the AudioSource component are in MumbleAudioPlayer.cs, which are only to start and stop and adjust volume. Any insight?

My setup: AudioListener on the main camera. The active AudioSource has Spatialize checked, Volume 1, Stereo Pan 0, Spatial Blend 1/3D, Spread 360, Logarithmic Rolloff, Max Distance 20.

**Comment by Bananahavoc** [comment]
Hmm, not sure what's happening for you. Spatialization definitely worked for me, but it has been quite a while since I worked on this. 

[Here](https://github.com/BananaHemic/Mumble-Unity/blob/1b20eba89ef3f77f5fd87b09afa2676a883c9c02/Scripts/MumbleAudioPlayer.cs#L89) is the code that gives unity mono audio.
