### ISSUE TITLE
Works in editor but not in build

### ISSUE THREAD

**Issue by Axios16** [BananaHemic/Mumble-Unity#26]
Everything works well in Editor, but if I launch the game standalone it doesn't connect to the server.

**Comment by Bananahavoc** [comment]
That's really not enough to go off of. Where does the connection fail, are there any exceptions/warnings?

**Comment by virusmarathe** [comment]
I am seeing something similar. When I start a new project in Unity2018.3.10f1, add the plugin, create a build, the client cannot joint the murmur server. In the murmur log it has message: "Connection: Failed to add flow to QOS"

**Comment by Bananahavoc** [comment]
That is very interesting. Do you know where that log message is being produced? Also, what platform is the built client running on?

**Comment by virusmarathe** [comment]
Windows, Message shows up in the Murmur Log window (right click show log)

**Comment by Bananahavoc** [comment]
So you're running Murmur on the same PC that is running Mumble-Unity, and that log is produced from Murmur? Are there any unusual logs from Mumble-Unity? Does the same thing happen if you connect to other servers?

**Comment by virusmarathe** [comment]
mm I've tried both, client on same machine, and client on another machine connecting in. I just tried connecting to another server, this time it stays stuck on "New connection : <my IP>" and doesn't have the QOS error, but still won't get to the authentication stage.

**Comment by virusmarathe** [comment]
nothing too crazy in the unity logs:
Using output sample rate: 48000
Using output channel count of: 2
<b>[SteamVR Interaction]</b> ChaperoneInfo initialized. Roomscale play area 1.73m x 1.33m
Will now connect
Device:  Microphone (2- Rift Audio) has freq: 48000 to 48000 setting to: 48000
Starting to send audio

**Comment by Bananahavoc** [comment]
I'm really not sure what the issue could be, there shouldn't be any major differences between editor and build. The only difference that I could think of would be differences in how windows/anti-virus affects your build vs the Unity Editor. You might want to experiment with disabling any firewalls and see if that helps.

I doubt this is relevant, but for the record I use Unity 2017.4.1

**Comment by virusmarathe** [comment]
I have tried it empty project 2017.4.1f1 and it works fine there. We recently upgraded to 2018 versions and it has stopped working.

**Comment by Axios16** [comment]
Hi! I solved the problem changing the API Compatibility to 4 in Unity
player settings

**Comment by Bananahavoc** [comment]
Awesome! Thanks for coming back with an update. @virusmarathe does that solve the problem for you? It would probably be good to add some precompiler statements to give a pragma warning when Unity doesn't have a high enough api compatibility

**Comment by virusmarathe** [comment]
oh cool, that works! Thank you
