### ISSUE TITLE
SSL Certification hangs

### ISSUE THREAD

**Issue by zakur0** [BananaHemic/Mumble-Unity#27]
I tried connecting to a local murmur server and to an online one. In both cases the connection hangs at  _ssl.AuthenticateAsClient(_hostname); in MumbleTCPConnection

**Comment by Bananahavoc** [comment]
What Unity version? Have you tried setting the API compatibility to 4? Does this happen in build and editor?

**Comment by zakur0** [comment]
I 'm using 2018.2.3f1 and I 'm using Scripting Runtime Version .Net 4.x Equivalent and Api Compatibility.Net 4.x

**Comment by Bananahavoc** [comment]
I'm not really sure what the issue could be. Does it happen only for one server, or any public mumble server?

**Comment by zakur0** [comment]
I tried both with public and private server. I 'm not sure why it happens, it works alright with .Net 3.5 but hangs with .Net 4 . I 've been reading issues from the forums like this one [unity forum thread](https://forum.unity.com/threads/unitywebrequest-unable-to-complete-ssl-connection.566380/) and it seems to be a problem on Unity's side :/

**Comment by Bananahavoc** [comment]
@zakur0 Did you find the cause of this issue? If not, I'd rather leave this open
