### ISSUE TITLE
opusthreshold is in murmur.ini, not mumble.ini

### ISSUE THREAD

**Issue by ArnoBen** [BananaHemic/Mumble-Unity#28]
I'm just pointing that because it took me a while before I realized you were talking about a file in murmur settings and not in Unity, and the file name with the opusthreshold is in murmur.ini, not in mumble.ini like you wrote in your readme.

Cheers

**Comment by Bananahavoc** [comment]
Seems like it's either murmur.ini or mumble-server.ini. I'll include both in the readme. Thanks for pointing this out!
