### ISSUE TITLE
NotSupportedException: This protocol version is not supported.

### ISSUE THREAD

**Issue by ArnoBen** [BananaHemic/Mumble-Unity#29]
Greetings,
I have a localhost murmur server and I simply launched the Example scene, changed the host name and clicked play. I get the error in the title when the following function is called in MumbleTCPConnection.cs : 
`_tcpClient.BeginConnect(_host.Address, _host.Port, new AsyncCallback(OnTcpConnected), null);`

Here is the complete error :

> NotSupportedException: This protocol version is not supported.
> System.Net.Sockets.Socket.BeginConnect (System.Net.IPAddress address, System.Int32 port, System.AsyncCallback requestCallback, System.Object state) (at <3845a180c26b4889bc2d47593a665814>:0)
> System.Net.Sockets.TcpClient.BeginConnect (System.Net.IPAddress address, System.Int32 port, System.AsyncCallback requestCallback, System.Object state) (at <3845a180c26b4889bc2d47593a665814>:0)
> Mumble.MumbleTcpConnection.StartClient (System.String username, System.String password) (at Assets/Scripts/MumbleTCPConnection.cs:55)
> Mumble.MumbleClient.Connect (System.String username, System.String password) (at Assets/Scripts/MumbleClient.cs:445)
> MumbleTester+<ConnectAsync>d__15.MoveNext () (at Assets/MumbleTester.cs:103)
> UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at C:/buildslave/unity/build/Runtime/Export/Coroutines.cs:17)

I'm trying to look on the Microsoft documentation but can't find a way to make it work. Does anyone have an idea on the matter ?

Thank you.

**Comment by ArnoBen** [comment]
After a few tests, this problem concerns the 2018 versions.
Concerning the 2019 version (2019.1), I have a NullReferenceException in MumbleClient.cs line 36 :
`public int NumUDPPacketsSent { get { return _udpConnection.NumPacketsSent; } }`
For the 2017 version, I have a "Connection failed!" error on localhost even though my server is running and I can connect to it with a regular mumble client.

**Comment by ArnoBen** [comment]
On the 2018 version, if I change the port, depending on the port number, I can get the error stated above : NullReferenceException: Object reference not set to an instance of an object on line 36 of MumbleClient.cs

**Comment by ArnoBen** [comment]
The issue in the title appears for all the ports up to 65536 (2^16 of course).

**Comment by ArnoBen** [comment]
Oh and a friend of mine gets the same error.

**Comment by Bananahavoc** [comment]
I haven't done any tests with the server running on localhost, so there could be some issues there that I hadn't anticipated. Can you check with a public mumble server?
Also, what is your api compatibility currently set to?

**Comment by ArnoBen** [comment]
It's indeed working with a random public server I picked. 
I'm using Api compatibility to .NET Standard 2.0 and scripting runtime 4.x, **however** when I use the scripting runtime version 3.5 instead, the error becomes `"Connection failed! Please confirm that you have internet access, and that the hostname is correct"`, which here is probably an error due to my server configuration. Unfortunately I have to use 4.x for other reasons.

**Comment by Bananahavoc** [comment]
I think the issue is that it doesn't get the address correctly for localhost servers. Before the _tcpClient.BeginConnect line, can you print what the _host.Address is?

**Comment by ArnoBen** [comment]
Yes that's it !
_host.Adress returns 0.0.0.1 when I put "localhost" as the adress, but the program works fine when I directly write "127.0.0.1".
Thank you very much for your support, I hope I'll be able to implement it smoothly in my project now that this problem is solved 😃

**Comment by Bananahavoc** [comment]
Glad to hear it!
If you feel like uploading a PR with that fix, I'd love to see it
