### ISSUE TITLE
Add per-speaker positional audio

### ISSUE THREAD

**Issue by Travelbug** [BananaHemic/Mumble-Unity#3]
I'm aware it is marked as todo. Is there any estimate on when this would be implemented? Or could you give me any directions on how to implement it myself? 

I didn't work with mumble so far. I need a VoIP solution for unity with spatial audio and this mumble client implementation looks promising. (the only promising solution I found to be honest..)

**Comment by Bananahavoc** [comment]
Actually, this should be marked as done. I just forgot to update the readme with the last group of commits
