### ISSUE TITLE
WebGL

### ISSUE THREAD

**Issue by Ewenoch** [BananaHemic/Mumble-Unity#32]
Thank you for your wonderfull work ... working really fine in standalone ... we are producing a webgl version of our appliaction ... i managed to get the webgl microphone, but i see that the opus lib that you delivered in your project dont fit for webGL... do you have a solution ? Thank you so much again 

Ewen

**Comment by Bananahavoc** [comment]
I don't have an opus lib compiled for webGL, but it should be possible as opus is just written in C. You might be able to grab a compiled opus lib from another networking asset that does support webGL, like Photon Voice for example.

That being said, the hard part of getting this asset working with webGL will likely be that this asset makes heavy use of UDP and TCP sockets, and in a browser the only equivalent that you'll have access to is a websocket.
