### ISSUE TITLE
Unity 2019 Can't find Opus.dll

### ISSUE THREAD

**Issue by Roamer79** [BananaHemic/Mumble-Unity#34]
Have upgraded an existing project from 2017 to 2019. Mumble was working perfectly now it can't find the Opus.dll even though it is there. Do you think with Unity 2019 forced .net 4.0 this could be the problem??

**Comment by Bananahavoc** [comment]
That certainly could be the case, I haven't used Unity 2019 yet so I'm not familiar with what's changed. You may also want to try reimporting that dll

**Comment by Roamer79** [comment]
I tried re-importing and unfortunately it didn't work. I am so bummed. I was forced to update to 2019 and I have tried all the other various Voip solutions and this one was by far the most reliable. :(( You should really get back on this project. Its great work. I'd pay to use it no problem.

**Comment by Bananahavoc** [comment]
I too really wish I could spend more time on this project (and other projects like it).

To the best of my recollection, Opus.dll is a C library, so I'm almost certain that it should in principal be able to run in 2019. It might be possible that the settings for the .dll need to be changed, or the import statements in C# need to be different. I wish I could be of more help here.

**Comment by Roamer79** [comment]
Hey, what if I was to make a donation to your paypal account to compensate your time to update this project??

**Comment by Roamer79** [comment]
Ok ive done some more investigating here. I got the opus.dll error cleared by using another build of it I found. Next issue. The clients won't connect and they just time out. I went back a version to 2018 and it all works fine. I just get this new connection on the server and then it timesout. Local client on the server connects fine. Any ideas where to look? Obviously big difference here is that Unity 2018 still allows .net3.5


![mumble](https://user-images.githubusercontent.com/41314882/68833092-bd93ce00-0706-11ea-9554-94df7b6eb2dc.png)

**Comment by Roamer79** [comment]
I wonder if its is a problem with the MumbleTCP/UDPConnection scripts. Looks like that is where it should authenticate the user and is has .net references.

**Comment by Bananahavoc** [comment]
It's possible that Protobuf also needs to be updated. You might want to uncomment [this line](https://github.com/BananaHemic/Mumble-Unity/blob/master/Scripts/MumbleTCPConnection.cs#L160) and see at what point the connection fails

**Comment by Roamer79** [comment]
Ok I un-commented the line and it doesn't log so it obviously isn't even getting to that point. In unity 2018 you can still switch between .net 3.5 and 4.0. I switch to 4 and its stops working, switch back to 3.5 and works fine. I am getting no errors whatsoever it just doesn't authenticate the client and timesout. I tried a .net 4.0 protbuf-net.dll and no good. :(

**Comment by Roamer79** [comment]
> 
> 
> It's possible that Protobuf also needs to be updated. You might want to uncomment [this line](https://github.com/BananaHemic/Mumble-Unity/blob/master/Scripts/MumbleTCPConnection.cs#L160) and see at what point the connection fails

Ill give you $500USD if you can sort this out to work with Unity 2019 .net 4.0. May only take you a couple of hrs.

**Comment by BananaHemic** [comment]
Deal, I'll get started on it now, you can email me at "brendanmlockhart" with gmail as the email provider
