### ISSUE TITLE
Whisper

### ISSUE THREAD

**Issue by Capantonio** [BananaHemic/Mumble-Unity#5]
How i can whisper to a client?
i find the function _manageSendBuffer.SendVoice(floatData, SpeechTarget.DirectWhisper1, 0), but i don't know where find the targetid to select the client i choose.

best regards,
Capitanio Fabio

**Comment by Bananahavoc** [comment]
Hey Capantonio,

Unfortunately that's not directly supported yet
Adding this shouldn't be too hard however. If you'd like to do this yourself (I'm low on time at the moment) you can get started by taking a look at ManageAudioSendBuffer line 105.

Feel free to reopen if you have any other questions
