### ISSUE TITLE
Create Git tag

### ISSUE THREAD

**Issue by bdovaz** [BananaHemic/Mumble-Unity#58]
OpenUPM requires tags per version to work properly, can you create one? Thanks!

https://openupm.com/packages/com.bananahemic.mumble/

**Comment by bdovaz** [comment]
@BananaHemic this issue is important to solve because otherwise all the work I did in another PR to be able to use it as a package and through OpenUPM is useless.

If you see that you can't dedicate enough time to this project I offer myself as a mantainer / contributor if you give me the appropriate permissions so this project doesn't die.

Thank you.

**Comment by Bananahavoc** [comment]
This should be done now, apologies on the delay.
