### ISSUE TITLE
ProtoBuf not found error

### ISSUE THREAD

**Issue by bhadrik-infivr** [BananaHemic/Mumble-Unity#59]
I am getting ProtoBuf not found error.

Here is how I setup the project

1. Created a new empty project, configured for windows build.
2. followed "installing method 1" given in readme.
3. Getting the following 500+ error.
[ERROR]: Library\PackageCache\com.bananahemic.mumble@1.0.0\Runtime\Scripts\MumbleTCPConnection.cs(2,7): error CS0246: The type or namespace name 'ProtoBuf' could not be found (are you missing a using directive or an assembly reference?)

Please help me how can I fix it.

**Comment by Bananahavoc** [comment]
@bdovaz Might have more information. You might need to add a Protobuf package. You may also want to use installation method 2.

**Comment by bhadrik-infivr** [comment]
Thanks for your reply I'll check this.

**Comment by bhadrik-infivr** [comment]
Great sir, working fine. Thank you so much. 🫡

**Comment by Bananahavoc** [comment]
Your welcome. Did you use installation method 2?

**Comment by bhadrik-infivr** [comment]
The issue was with the openUPM install. If I install Mumble-Unity using OpenUPM then it is unable to use ProtoBuf. So I just git clone this repo and removed from openUPM it worked for me.
