### ISSUE TITLE
Positional Audio? How integrate in Unity Project?

### ISSUE THREAD

**Issue by Vytek** [BananaHemic/Mumble-Unity#6]
In README you say:

Different audio positions for each Mumble speaker is not yet supported, but is possible

How can integrate this feature in little Social Demo?

My project is Open Source and based on Unity 5.6.1f1.

Thanks for your work and help!

**Comment by Bananahavoc** [comment]
I'm going to remove that line.

If you take a look at MumbleTester, you'll see that when creating the mumble client you pass a method "CreateMumbleAudioPlayerFromPrefab". This method is called whenever a new user is in the Mumble room. It's here that you can make the new mumble audio player be a child object to something, and change its positional.

Let me know if you have any other questions, or if I can close this

**Comment by Vytek** [comment]
Thank you for your answer. So I had to modify this method to create a child object of my user/avatat head using: http://answers.unity3d.com/questions/572176/how-can-i-instantiate-a-gameobject-directly-into-a-1.html ?

` private MumbleAudioPlayer CreateMumbleAudioPlayerFromPrefab()
    {`

**Comment by Bananahavoc** [comment]
Yep, that's the one. I'll make some changes to the README to make that more clear. Feel free to reopen or make a new ticket if anything else is unclear
