### ISSUE TITLE
Trouble with more than one istantiated object?

### ISSUE THREAD

**Issue by Vytek** [BananaHemic/Mumble-Unity#8]
I started developing my social VR using your awesome MumbleUnity component.
I cannot manage to distinguish each connected user from each other, which is necessary in order to associate every mumble object to its owner.
At every new connection , it is easy to istantiate the new user/player, and associating the new MumbleAudioPlayer. 
However, starting from two players on, every new user receives its object , but cannot distinguish which of the two objects he finds (o1, o2) belongs to User A or User B.

How can I "label" every MumbleAudioPlayer with its owner?

**Comment by Bananahavoc** [comment]
I'm glad to hear you like the asset! I just pushed an additional method for MumbleAudioPlayer that retrieves the username of the speaker that it's connected to. I think that will help you with your issue. Feel free to reopen this if I misread your issue.

Good luck on your social VR project!

**Comment by Vytek** [comment]
Thank you very much!

**Comment by Vytek** [comment]
I am checking your add to the code and I have problem with the modified function: CreateMumbleAudioPlayerFromPrefab()
"GetUsername()" return always a null object :'-(

![clipboard02](https://user-images.githubusercontent.com/2614303/32138105-a0079720-bc2d-11e7-8b88-cb5e85d47fc9.png)
![clipboard03](https://user-images.githubusercontent.com/2614303/32138106-a3e9095a-bc2d-11e7-8079-fdda9eb094b5.png)

Please, help me check that I am using it right. 
This is my code:
```
private MumbleAudioPlayer CreateMumbleAudioPlayerFromPrefab()
{
	// Depending on your use case, you might want to add the prefab to an existing object (like someone's head)
	// If you have users entering and leaving frequently, you might want to implement an object pool
	GameObject newObj = GameObject.Instantiate(MyMumbleAudioPlayerPrefab);
	{
		Debug.Log("Mumbers PlayerGameObjects: " + PlayerGameObjectTracker.AllPlayerGameObjects.Count);
		foreach (GameObject PGO in PlayerGameObjectTracker.AllPlayerGameObjects)
		{
			//https://github.com/BananaHemic/Mumble-Unity/commit/f77a05b5c9a7a65aea4cafd887ed6250ff86fab2
			//https://github.com/BananaHemic/Mumble-Unity/issues/8
			if (newObj.GetComponent<MumbleAudioPlayer>().GetUsername()==null)
			{
				Debug.Log("Mumble UserName is null");
				Debug.Log("Mumble UserName: " + newObj.GetComponent<MumbleAudioPlayer>().GetUsername());
			}
			Debug.Log("------------------------------------");
			Debug.Log("Avatar UserName: " + PGO.GetComponent<NetworkPlayerParent>().AvatarName);
			if (newObj.GetComponent<MumbleAudioPlayer>().GetUsername() == PGO.GetComponent<NetworkPlayerParent>().AvatarName)
			{
				Debug.Log("Attach MumbleAudioPlayer: " + newObj.GetComponent<MumbleAudioPlayer>().GetUsername() + " to: "+PGO.name);
				newObj.transform.parent = PGO.transform.Find("Head").gameObject.transform;
			}
		}
	}
	MumbleAudioPlayer newPlayer = newObj.GetComponent<MumbleAudioPlayer>();
	return newPlayer;
}
```

**Comment by Bananahavoc** [comment]
This was because the prefab instantiation was occurring before the audio player script had been initialized. I hadn't planned for the username to be available when that method is called, but it seems like having that could be useful. I just pushed a commit that adds a username string to CreateMumbleAudioPlayerFromPrefab, that should fix the issue. Hopefully that solves your problem!

**Comment by Vytek** [comment]
It works fine! Thank you very much!
